#!/usr/bin/env python3
"""Nova reconciler.

Runs at agent STARTUP -- after every provider/channel kit has written its
fragment into agent-context.d at build time. This is how Nova 'gets the last
word' and configures itself in the presence of whatever kits were applied,
WITHOUT any sbx engine lifecycle change.

Nova renders its native format: TOML. (Atlas renders JSON from the same input.)
Stdlib only -- this runs inside the sandbox with no extra deps.
"""
import glob
import json
import os
import sys

CONTEXT_DIR = os.environ.get("AGENT_CONTEXT_DIR", "/etc/sbx/agent-context.d")
OUT = os.environ.get("NOVA_CONFIG", "/home/agent/nova/nova.toml")


def load_fragments():
    frags = []
    for path in sorted(glob.glob(os.path.join(CONTEXT_DIR, "*.json"))):
        with open(path) as f:
            frags.append(json.load(f))
    return frags


def toml_str(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    frags = load_fragments()
    providers = [f for f in frags if f.get("config", {}).get("role") == "llm-provider"]
    channels = [f for f in frags if f.get("config", {}).get("role") == "messaging-channel"]

    # The agent owns conflict resolution -- it decides what to do when zero or
    # many providers are present. Here: exactly one provider is required.
    if len(providers) != 1:
        sys.exit(f"nova: need exactly one llm-provider in {CONTEXT_DIR}, found {len(providers)}")

    p = providers[0]["config"]
    lines = [
        "# generated by nova reconcile from agent-context.d",
        "",
        "[provider]",
        f"api_style = {toml_str(p['apiStyle'])}",
        f"base_url = {toml_str(p['baseUrl'])}",
        f"llm_model = {toml_str(p['models']['llm'])}",
        f"embedder_model = {toml_str(p['models']['embedder'])}",
        f"api_key_ref = {toml_str(p['auth']['secretRef'])}",
    ]
    for ch in channels:
        c = ch["config"]
        lines += [
            "",
            "[[channel]]",
            f"transport = {toml_str(c['transport'])}",
            f"token_ref = {toml_str(c['auth']['secretRef'])}",
        ]

    out = "\n".join(lines) + "\n"
    out_dir = os.path.dirname(OUT)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(OUT, "w") as f:
        f.write(out)

    secret_refs = sorted({s["ref"] for fr in frags for s in fr.get("secrets", [])})
    print(out, end="")
    print(f"# secrets needed (refs only, resolved by the sbx proxy): {', '.join(secret_refs)}")


if __name__ == "__main__":
    main()
